---
# roles/common/tasks/main.yml
# This file contains tasks that are common to all hosts or used to deploy the FastAPI application.

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install required system packages
  apt:
    name:
      - python3
      - python3-pip
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
    state: present
  become: yes

- name: Install FastAPI and Uvicorn using pip
  pip:
    name:
      - fastapi
      - "uvicorn[standard]"
    executable: pip3

- name: Copy FastAPI application files
  copy:
    src: "{{ playbook_dir }}/../app/"   # Adjust the source path as needed.
    dest: "/opt/{{ app_name }}/"
  become: yes
